CREATE DATABASE foodfy

CREATE TABLE chefs (
    ID INTEGER SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    FILE_ID INTEGER NOT NULL REFERENCES files(id)
)

CREATE TABLE recipes (
    ID INTEGER SERIAL PRIMARY KEY,
    CHEF_ID INTEGER NOT NULL REFERENCES chefs(id),
    IMAGE TEXT NOT NULL,
    TITLE TEXT NOT NULL,
    INGREDIENTS TEXT[] NOT NULL,
    PREPARATION TEXT[] NOT NULL,
    INFORMATION TEXT,
    CREATED_AT TIMESTAMP NOT NULL
)

CREATE TABLE files (
    ID SERIAL PRIMARY KEY,
    NAME TEXT,
    PATH TEXT NOT NULL
)

CREATE TABLE recipe_files (
    ID SERIAL PRIMARY KEY
    RECIPE_ID INTEGER REFERENCES recipes(id)
    FILE_ID INTEGER REFERENCES files(id)
)
